  // Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SelectBarTestTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void selectBarTest() {
    // Test name: SelectBarTest
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("http://localhost:8081/");
    // 2 | setWindowSize | 1552x840 | 
    driver.manage().window().setSize(new Dimension(1552, 840));
    // 3 | click | id=getCityInfo2 | 
    driver.findElement(By.id("getCityInfo2")).click();
    // 4 | click | css=.w3-third:nth-child(1) > .w3-card | 
    driver.findElement(By.cssSelector(".w3-third:nth-child(1) > .w3-card")).click();
    // 5 | assertText | id=select_err | City not found.
    assertThat(driver.findElement(By.id("select_err")).getText(), is("City not found."));
    // 6 | click | id=city2 | 
    driver.findElement(By.id("city2")).click();
    // 7 | select | id=city2 | label=Paris
    {
      WebElement dropdown = driver.findElement(By.id("city2"));
      dropdown.findElement(By.xpath("//option[. = 'Paris']")).click();
    }
    // 8 | click | id=city2 | 
    driver.findElement(By.id("city2")).click();
    // 9 | click | id=getCityInfo2 | 
    driver.findElement(By.id("getCityInfo2")).click();
  }
}
